/*
    Copyright 2009 Eurocom Entertainment Software Limited

    This file is part of Plisgo.

    Eurocom Entertainment Software Limited, hereby disclaims all
    copyright interest in “Plisgo” written by Joe Burmeister.

    Plisgo is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Plisgo is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Plisgo.  If not, see <http://www.gnu.org/licenses/>.
*/

// This file will be processed by the MIDL tool to
// produce the type library (Plisgo.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(01AAB0B6-BBF0-41D8-93EC-D1D33CC97F90),
	dual,
	nonextensible,
	helpstring("IPlisgoFolder Interface"),
	pointer_default(unique)
]
interface IPlisgoFolder : IDispatch{
};
[
	object,
	uuid(54B1AF8E-C9C3-4B0D-849E-E9922A9B08AC),
	dual,
	nonextensible,
	helpstring("IPlisgoExtractIcon Interface"),
	pointer_default(unique)
]
interface IPlisgoExtractIcon : IDispatch{
};
[
	object,
	uuid(67876E11-00DD-4769-B6EF-DAB4C647851B),
	dual,
	nonextensible,
	helpstring("IPlisgoView Interface"),
	pointer_default(unique)
]
interface IPlisgoView : IDispatch{
};
[
	object,
	uuid(0D761E7E-9D3C-41FE-B250-C181AE25BD89),
	dual,
	nonextensible,
	helpstring("IPlisgoMenu Interface"),
	pointer_default(unique)
]
interface IPlisgoMenu : IDispatch{
};
[
	object,
	uuid(FF9CD024-4DF9-43F5-BEF1-7A79D5A1C844),
	dual,
	nonextensible,
	helpstring("IPlisgoData Interface"),
	pointer_default(unique)
]
interface IPlisgoData : IDispatch{
};
[
	object,
	uuid(B12ADF19-B092-445B-9468-3E190A16C424),
	dual,
	nonextensible,
	helpstring("IPlisgoEnumFORMATETC Interface"),
	pointer_default(unique)
]
interface IPlisgoEnumFORMATETC : IDispatch{
};
[
	object,
	uuid(4A8859C3-EB36-42DC-A5C7-96EFF3BBFD64),
	dual,
	nonextensible,
	helpstring("IPlisgoDropSource Interface"),
	pointer_default(unique)
]
interface IPlisgoDropSource : IDispatch{
};
[
	uuid(68DDD719-C3B0-48D0-B5BB-1351B3AE71E8),
	version(1.0),
	helpstring("Plisgo 1.0 Type Library")
]
library PlisgoLib
{
	importlib("stdole2.tlb");
	[
		uuid(ADA19F85-EEB6-46F2-B8B2-2BD977934A79),
		helpstring("PlisgoFolder Class")
	]
	coclass PlisgoFolder
	{
		[default] interface IPlisgoFolder;
	};
	[
		uuid(11E54957-7EED-4F3C-A4C1-46788757EC62),
		helpstring("PlisgoExtractIcon Class")
	]
	coclass PlisgoExtractIcon
	{
		[default] interface IPlisgoExtractIcon;
	};
	[
		uuid(E8716A04-546B-4DB1-BB55-0A230E20A0C5),
		helpstring("PlisgoView Class")
	]
	coclass PlisgoView
	{
		[default] interface IPlisgoView;
	};
	[
		uuid(BBF30838-6C39-4D2B-83FA-4654A3725674),
		helpstring("PlisgoMenu Class")
	]
	coclass PlisgoMenu
	{
		[default] interface IPlisgoMenu;
	};
	[
		uuid(3F57F545-286B-4881-8484-466812610AC8),
		helpstring("PlisgoData Class")
	]
	coclass PlisgoData
	{
		[default] interface IPlisgoData;
	};
	[
		uuid(41788118-D766-476B-A44A-9DA50DD1B96D),
		helpstring("PlisgoEnumFORMATETC Class")
	]
	coclass PlisgoEnumFORMATETC
	{
		[default] interface IPlisgoEnumFORMATETC;
	};
	[
		uuid(257BAE7D-AD3C-4F0F-9232-B9B18E546106),
		helpstring("PlisgoDropSource Class")
	]
	coclass PlisgoDropSource
	{
		[default] interface IPlisgoDropSource;
	};
};
